### PR TITLE
build: fix build issue in 0.5.5

### PR DESCRIPTION
**Pull request by TimoGlastra**
Fixes the build issue introduced in 0.5.5. We'll have to do a 0.5.6 release sadly.

It does add a few nice improvements though:
- now also includes src in package.json
- source maps point to source files, so whenever you now click on a type / method in e.g. vscode from credo you will be shown the source TS code rather than the build js code. Making debugging a lot easier I'd say :)

### CODE REVIEW

**Review by berendsliedrecht — APPROVED** [review]
How will this influence the bundle size? Including the `src` directory can have quite an impact, right?

**Comment by TimoGlastra** [comment]
Yeah it has some impact on the bundle size as you include the src, but I think it's well worth it because of the goto source now actually works and that makes debugging a lot easier.

**Comment by berendsliedrecht** [comment]
> Yeah it has some impact on the bundle size as you include the src, but I think it's well worth it because of the goto source now actually works and that makes debugging a lot easier.

If it is included in the final production bundle, I am not sure I think it is worth it. Unpacked size of `@credo-ts/core` is already 4.7MB. Now, with the `src` it will be more than double so likely something around 10MB (for just core!) and if we also include atleast `libaskar.so` we will add another 5-7 MB... This is getting really big IMO.

**Comment by TimoGlastra** [comment]
Okay -- now released 0.5.6 as there was a build issue with 0.5.5. I'll look into it again. I like it when packages publish source code, but if it's not desired it's easy to not do it

**Pull request merged**
